"""add visao cliente staging and final tables

Revision ID: 20260227_000002
Revises: 20260227_000001
Create Date: 2026-02-27 00:00:02
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "20260227_000002"
down_revision: Union[str, None] = "20260227_000001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "staging_visao_cliente",
        sa.Column('data_base', sa.Text(), nullable=True),
        sa.Column('cd_cpf_cnpj_cliente', sa.Text(), nullable=True),
        sa.Column('nome_cliente', sa.Text(), nullable=True),
        sa.Column('tipo_pessoa', sa.Text(), nullable=True),
        sa.Column('cd_cpf_cnpj_parceiro', sa.Text(), nullable=True),
        sa.Column('nome_parceiro', sa.Text(), nullable=True),
        sa.Column('cd_cpf_cnpj_consultor', sa.Text(), nullable=True),
        sa.Column('nome_consultor', sa.Text(), nullable=True),
        sa.Column('uf', sa.Text(), nullable=True),
        sa.Column('cidade', sa.Text(), nullable=True),
        sa.Column('bairro', sa.Text(), nullable=True),
        sa.Column('telefone', sa.Text(), nullable=True),
        sa.Column('telefone_master', sa.Text(), nullable=True),
        sa.Column('email', sa.Text(), nullable=True),
        sa.Column('dt_fundacao_empresa', sa.Text(), nullable=True),
        sa.Column('ramo_atuacao', sa.Text(), nullable=True),
        sa.Column('num_conta', sa.Text(), nullable=True),
        sa.Column('limite_conta', sa.Text(), nullable=True),
        sa.Column('dt_conta_criada', sa.Text(), nullable=True),
        sa.Column('dt_encer_cc', sa.Text(), nullable=True),
        sa.Column('status_cc', sa.Text(), nullable=True),
        sa.Column('conta_ativa_90d', sa.Text(), nullable=True),
        sa.Column('chaves_pix_forte', sa.Text(), nullable=True),
        sa.Column('vl_cash_in_mtd', sa.Text(), nullable=True),
        sa.Column('limite_cartao', sa.Text(), nullable=True),
        sa.Column('limite_alocado_cartao_cdb', sa.Text(), nullable=True),
        sa.Column('dt_entrega_cartao', sa.Text(), nullable=True),
        sa.Column('dt_ativ_cartao_cred', sa.Text(), nullable=True),
        sa.Column('vl_spending_total_mtd', sa.Text(), nullable=True),
        sa.Column('status_pagamento_fatura', sa.Text(), nullable=True),
        sa.Column('fl_propensao_c6pay', sa.Text(), nullable=True),
        sa.Column('tpv_c6pay_potencial', sa.Text(), nullable=True),
        sa.Column('fl_elegivel_venda_c6pay', sa.Text(), nullable=True),
        sa.Column('status_proposta_sf_pay', sa.Text(), nullable=True),
        sa.Column('dt_aprovacao_pay', sa.Text(), nullable=True),
        sa.Column('dt_install_maq', sa.Text(), nullable=True),
        sa.Column('dt_ativacao_pay', sa.Text(), nullable=True),
        sa.Column('c6pay_ativa_30', sa.Text(), nullable=True),
        sa.Column('dt_cancelamento_maq', sa.Text(), nullable=True),
        sa.Column('dt_ult_trans_pay', sa.Text(), nullable=True),
        sa.Column('recebimento', sa.Text(), nullable=True),
        sa.Column('banco_domicilio', sa.Text(), nullable=True),
        sa.Column('tpv_m2', sa.Text(), nullable=True),
        sa.Column('tpv_m1', sa.Text(), nullable=True),
        sa.Column('tpv_m0', sa.Text(), nullable=True),
        sa.Column('faixa_tpv_prometido', sa.Text(), nullable=True),
        sa.Column('fl_propensao_bolcob', sa.Text(), nullable=True),
        sa.Column('tpv_bolcob_potencial', sa.Text(), nullable=True),
        sa.Column('fl_bolcob_cadastrado', sa.Text(), nullable=True),
        sa.Column('dt_prim_liq_bolcob', sa.Text(), nullable=True),
        sa.Column('dt_ult_emissao_bolcob', sa.Text(), nullable=True),
        sa.Column('qtd_bolcob_emtd_mtd', sa.Text(), nullable=True),
        sa.Column('vl_bolcob_emtd_mtd', sa.Text(), nullable=True),
        sa.Column('qtd_bolcob_liq_mtd', sa.Text(), nullable=True),
        sa.Column('vl_bolcob_liq_mtd', sa.Text(), nullable=True),
        sa.Column('volume_antecipado', sa.Text(), nullable=True),
        sa.Column('agenda_disponivel', sa.Text(), nullable=True),
        sa.Column('taxa_antecipacao', sa.Text(), nullable=True),
        sa.Column('vl_saldo_medio_mensalizado', sa.Text(), nullable=True),
        sa.Column('dt_conta_criada_global', sa.Text(), nullable=True),
        sa.Column('vl_cash_in_conta_global_mtd', sa.Text(), nullable=True),
        sa.Column('fl_cash_in_puro', sa.Text(), nullable=True),
        sa.Column('fl_cash_in_boleto', sa.Text(), nullable=True),
        sa.Column('fl_cash_in_setup', sa.Text(), nullable=True),
        sa.Column('fl_cash_in_setup_pix_cnpj', sa.Text(), nullable=True),
        sa.Column('fl_cash_in_setup_cdb_cartao', sa.Text(), nullable=True),
        sa.Column('fl_cash_in_setup_pagamentos', sa.Text(), nullable=True),
        sa.Column('fl_cash_in_setup_deb_auto', sa.Text(), nullable=True),
        sa.Column('mes_ref_comiss', sa.Text(), nullable=True),
        sa.Column('fl_qualificado_comiss', sa.Text(), nullable=True),
        sa.Column('faixa_cash_in', sa.Text(), nullable=True),
        sa.Column('faixa_domicilio', sa.Text(), nullable=True),
        sa.Column('faixa_saldo_medio', sa.Text(), nullable=True),
        sa.Column('faixa_spending', sa.Text(), nullable=True),
        sa.Column('faixa_cash_in_global', sa.Text(), nullable=True),
        sa.Column('criterios_atingidos_comiss', sa.Text(), nullable=True),
        sa.Column('apuracao_comiss', sa.Text(), nullable=True),
        sa.Column('multiplicador', sa.Text(), nullable=True),
        sa.Column('ja_pago_comiss', sa.Text(), nullable=True),
        sa.Column('previsao_comiss', sa.Text(), nullable=True),
        sa.Column('faixa_max', sa.Text(), nullable=True),
        sa.Column('faixa_alvo', sa.Text(), nullable=True),
        sa.Column('threshiold_cash_in', sa.Text(), nullable=True),
        sa.Column('threshold_spending', sa.Text(), nullable=True),
        sa.Column('threshold_saldo_medio', sa.Text(), nullable=True),
        sa.Column('threshold_conta_global', sa.Text(), nullable=True),
        sa.Column('threshold_domicilio', sa.Text(), nullable=True),
        sa.Column('gap_cash_in', sa.Text(), nullable=True),
        sa.Column('gap_spending', sa.Text(), nullable=True),
        sa.Column('gap_saldo_medio', sa.Text(), nullable=True),
        sa.Column('gap_conta_global', sa.Text(), nullable=True),
        sa.Column('gap_domicilio', sa.Text(), nullable=True),
        sa.Column('pct_cash_in', sa.Text(), nullable=True),
        sa.Column('pct_spending', sa.Text(), nullable=True),
        sa.Column('pct_saldo_medio', sa.Text(), nullable=True),
        sa.Column('pct_conta_global', sa.Text(), nullable=True),
        sa.Column('maior_progresso_pct', sa.Text(), nullable=True),
        sa.Column('criterio_proximo', sa.Text(), nullable=True),
        sa.Column('ja_recebeu_comissao', sa.Text(), nullable=True),
        sa.Column('comissao_prox_mes', sa.Text(), nullable=True),
        sa.Column('status_qualificacao', sa.Text(), nullable=True),
        sa.Column('dias_desde_abertura', sa.Text(), nullable=True),
        sa.Column('m2_dias_faltantes', sa.Text(), nullable=True),
        sa.Column("etl_job_id", sa.String(length=36), nullable=False),
        sa.Column("loaded_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_staging_visao_cliente_etl_job_id", "staging_visao_cliente", ["etl_job_id"])

    op.create_table(
        "final_visao_cliente",
        sa.Column('data_base', sa.Text(), nullable=True),
        sa.Column('cd_cpf_cnpj_cliente', sa.Text(), nullable=True),
        sa.Column('nome_cliente', sa.Text(), nullable=True),
        sa.Column('tipo_pessoa', sa.Text(), nullable=True),
        sa.Column('cd_cpf_cnpj_parceiro', sa.Text(), nullable=True),
        sa.Column('nome_parceiro', sa.Text(), nullable=True),
        sa.Column('cd_cpf_cnpj_consultor', sa.Text(), nullable=True),
        sa.Column('nome_consultor', sa.Text(), nullable=True),
        sa.Column('uf', sa.Text(), nullable=True),
        sa.Column('cidade', sa.Text(), nullable=True),
        sa.Column('bairro', sa.Text(), nullable=True),
        sa.Column('telefone', sa.Text(), nullable=True),
        sa.Column('telefone_master', sa.Text(), nullable=True),
        sa.Column('email', sa.Text(), nullable=True),
        sa.Column('dt_fundacao_empresa', sa.Text(), nullable=True),
        sa.Column('ramo_atuacao', sa.Text(), nullable=True),
        sa.Column('num_conta', sa.Text(), nullable=True),
        sa.Column('limite_conta', sa.Text(), nullable=True),
        sa.Column('dt_conta_criada', sa.Text(), nullable=True),
        sa.Column('dt_encer_cc', sa.Text(), nullable=True),
        sa.Column('status_cc', sa.Text(), nullable=True),
        sa.Column('conta_ativa_90d', sa.Text(), nullable=True),
        sa.Column('chaves_pix_forte', sa.Text(), nullable=True),
        sa.Column('vl_cash_in_mtd', sa.Text(), nullable=True),
        sa.Column('limite_cartao', sa.Text(), nullable=True),
        sa.Column('limite_alocado_cartao_cdb', sa.Text(), nullable=True),
        sa.Column('dt_entrega_cartao', sa.Text(), nullable=True),
        sa.Column('dt_ativ_cartao_cred', sa.Text(), nullable=True),
        sa.Column('vl_spending_total_mtd', sa.Text(), nullable=True),
        sa.Column('status_pagamento_fatura', sa.Text(), nullable=True),
        sa.Column('fl_propensao_c6pay', sa.Text(), nullable=True),
        sa.Column('tpv_c6pay_potencial', sa.Text(), nullable=True),
        sa.Column('fl_elegivel_venda_c6pay', sa.Text(), nullable=True),
        sa.Column('status_proposta_sf_pay', sa.Text(), nullable=True),
        sa.Column('dt_aprovacao_pay', sa.Text(), nullable=True),
        sa.Column('dt_install_maq', sa.Text(), nullable=True),
        sa.Column('dt_ativacao_pay', sa.Text(), nullable=True),
        sa.Column('c6pay_ativa_30', sa.Text(), nullable=True),
        sa.Column('dt_cancelamento_maq', sa.Text(), nullable=True),
        sa.Column('dt_ult_trans_pay', sa.Text(), nullable=True),
        sa.Column('recebimento', sa.Text(), nullable=True),
        sa.Column('banco_domicilio', sa.Text(), nullable=True),
        sa.Column('tpv_m2', sa.Text(), nullable=True),
        sa.Column('tpv_m1', sa.Text(), nullable=True),
        sa.Column('tpv_m0', sa.Text(), nullable=True),
        sa.Column('faixa_tpv_prometido', sa.Text(), nullable=True),
        sa.Column('fl_propensao_bolcob', sa.Text(), nullable=True),
        sa.Column('tpv_bolcob_potencial', sa.Text(), nullable=True),
        sa.Column('fl_bolcob_cadastrado', sa.Text(), nullable=True),
        sa.Column('dt_prim_liq_bolcob', sa.Text(), nullable=True),
        sa.Column('dt_ult_emissao_bolcob', sa.Text(), nullable=True),
        sa.Column('qtd_bolcob_emtd_mtd', sa.Text(), nullable=True),
        sa.Column('vl_bolcob_emtd_mtd', sa.Text(), nullable=True),
        sa.Column('qtd_bolcob_liq_mtd', sa.Text(), nullable=True),
        sa.Column('vl_bolcob_liq_mtd', sa.Text(), nullable=True),
        sa.Column('volume_antecipado', sa.Text(), nullable=True),
        sa.Column('agenda_disponivel', sa.Text(), nullable=True),
        sa.Column('taxa_antecipacao', sa.Text(), nullable=True),
        sa.Column('vl_saldo_medio_mensalizado', sa.Text(), nullable=True),
        sa.Column('dt_conta_criada_global', sa.Text(), nullable=True),
        sa.Column('vl_cash_in_conta_global_mtd', sa.Text(), nullable=True),
        sa.Column('fl_cash_in_puro', sa.Text(), nullable=True),
        sa.Column('fl_cash_in_boleto', sa.Text(), nullable=True),
        sa.Column('fl_cash_in_setup', sa.Text(), nullable=True),
        sa.Column('fl_cash_in_setup_pix_cnpj', sa.Text(), nullable=True),
        sa.Column('fl_cash_in_setup_cdb_cartao', sa.Text(), nullable=True),
        sa.Column('fl_cash_in_setup_pagamentos', sa.Text(), nullable=True),
        sa.Column('fl_cash_in_setup_deb_auto', sa.Text(), nullable=True),
        sa.Column('mes_ref_comiss', sa.Text(), nullable=True),
        sa.Column('fl_qualificado_comiss', sa.Text(), nullable=True),
        sa.Column('faixa_cash_in', sa.Text(), nullable=True),
        sa.Column('faixa_domicilio', sa.Text(), nullable=True),
        sa.Column('faixa_saldo_medio', sa.Text(), nullable=True),
        sa.Column('faixa_spending', sa.Text(), nullable=True),
        sa.Column('faixa_cash_in_global', sa.Text(), nullable=True),
        sa.Column('criterios_atingidos_comiss', sa.Text(), nullable=True),
        sa.Column('apuracao_comiss', sa.Text(), nullable=True),
        sa.Column('multiplicador', sa.Text(), nullable=True),
        sa.Column('ja_pago_comiss', sa.Text(), nullable=True),
        sa.Column('previsao_comiss', sa.Text(), nullable=True),
        sa.Column('faixa_max', sa.Text(), nullable=True),
        sa.Column('faixa_alvo', sa.Text(), nullable=True),
        sa.Column('threshiold_cash_in', sa.Text(), nullable=True),
        sa.Column('threshold_spending', sa.Text(), nullable=True),
        sa.Column('threshold_saldo_medio', sa.Text(), nullable=True),
        sa.Column('threshold_conta_global', sa.Text(), nullable=True),
        sa.Column('threshold_domicilio', sa.Text(), nullable=True),
        sa.Column('gap_cash_in', sa.Text(), nullable=True),
        sa.Column('gap_spending', sa.Text(), nullable=True),
        sa.Column('gap_saldo_medio', sa.Text(), nullable=True),
        sa.Column('gap_conta_global', sa.Text(), nullable=True),
        sa.Column('gap_domicilio', sa.Text(), nullable=True),
        sa.Column('pct_cash_in', sa.Text(), nullable=True),
        sa.Column('pct_spending', sa.Text(), nullable=True),
        sa.Column('pct_saldo_medio', sa.Text(), nullable=True),
        sa.Column('pct_conta_global', sa.Text(), nullable=True),
        sa.Column('maior_progresso_pct', sa.Text(), nullable=True),
        sa.Column('criterio_proximo', sa.Text(), nullable=True),
        sa.Column('ja_recebeu_comissao', sa.Text(), nullable=True),
        sa.Column('comissao_prox_mes', sa.Text(), nullable=True),
        sa.Column('status_qualificacao', sa.Text(), nullable=True),
        sa.Column('dias_desde_abertura', sa.Text(), nullable=True),
        sa.Column('m2_dias_faltantes', sa.Text(), nullable=True),
        sa.UniqueConstraint('data_base', 'cd_cpf_cnpj_cliente', name="uq_final_visao_cliente_base_cliente"),
    )


def downgrade() -> None:
    op.drop_table("final_visao_cliente")
    op.drop_index("ix_staging_visao_cliente_etl_job_id", table_name="staging_visao_cliente")
    op.drop_table("staging_visao_cliente")
