import re
import unicodedata

SOURCE_SHEET_NAME = "Visão Cliente"
STAGING_TABLE_NAME = "staging_visao_cliente"
FINAL_TABLE_NAME = "final_visao_cliente"
UPSERT_CONFLICT_COLUMNS = ("cd_cpf_cnpj_cliente",)
UPSERT_CONFLICT_WHERE = "cd_cpf_cnpj_cliente IS NOT NULL"

REQUIRED_COLUMNS = [
    "data_base",
    "cd_cpf_cnpj_cliente",
    "nome_cliente",
    "tipo_pessoa",
    "cd_cpf_cnpj_parceiro",
    "nome_parceiro",
    "cd_cpf_cnpj_consultor",
    "nome_consultor",
    "uf",
    "cidade",
    "bairro",
    "telefone",
    "telefone_master",
    "email",
    "dt_fundacao_empresa",
    "ramo_atuacao",
    "num_conta",
    "limite_conta",
    "dt_conta_criada",
    "dt_encer_cc",
    "status_cc",
    "conta_ativa_90d",
    "chaves_pix_forte",
    "vl_cash_in_mtd",
    "limite_cartao",
    "limite_alocado_cartao_cdb",
    "dt_entrega_cartao",
    "dt_ativ_cartao_cred",
    "vl_spending_total_mtd",
    "status_pagamento_fatura",
    "fl_propensao_c6pay",
    "tpv_c6pay_potencial",
    "fl_elegivel_venda_c6pay",
    "status_proposta_sf_pay",
    "dt_aprovacao_pay",
    "dt_install_maq",
    "dt_ativacao_pay",
    "c6pay_ativa_30",
    "dt_cancelamento_maq",
    "dt_ult_trans_pay",
    "recebimento",
    "banco_domicilio",
    "tpv_m2",
    "tpv_m1",
    "tpv_m0",
    "faixa_tpv_prometido",
    "fl_propensao_bolcob",
    "tpv_bolcob_potencial",
    "fl_bolcob_cadastrado",
    "dt_prim_liq_bolcob",
    "dt_ult_emissao_bolcob",
    "qtd_bolcob_emtd_mtd",
    "vl_bolcob_emtd_mtd",
    "qtd_bolcob_liq_mtd",
    "vl_bolcob_liq_mtd",
    "volume_antecipado",
    "agenda_disponivel",
    "taxa_antecipacao",
    "vl_saldo_medio_mensalizado",
    "dt_conta_criada_global",
    "vl_cash_in_conta_global_mtd",
    "fl_cash_in_puro",
    "fl_cash_in_boleto",
    "fl_cash_in_setup",
    "fl_cash_in_setup_pix_cnpj",
    "fl_cash_in_setup_cdb_cartao",
    "fl_cash_in_setup_pagamentos",
    "fl_cash_in_setup_deb_auto",
    "mes_ref_comiss",
    "fl_qualificado_comiss",
    "faixa_cash_in",
    "faixa_domicilio",
    "faixa_saldo_medio",
    "faixa_spending",
    "faixa_cash_in_global",
    "criterios_atingidos_comiss",
    "apuracao_comiss",
    "multiplicador",
    "ja_pago_comiss",
    "previsao_comiss",
    "faixa_max",
    "faixa_alvo",
    "threshiold_cash_in",
    "threshold_spending",
    "threshold_saldo_medio",
    "threshold_conta_global",
    "threshold_domicilio",
    "gap_cash_in",
    "gap_spending",
    "gap_saldo_medio",
    "gap_conta_global",
    "gap_domicilio",
    "pct_cash_in",
    "pct_spending",
    "pct_saldo_medio",
    "pct_conta_global",
    "maior_progresso_pct",
    "criterio_proximo",
    "ja_recebeu_comissao",
    "comissao_prox_mes",
    "status_qualificacao",
    "dias_desde_abertura",
    "m2_dias_faltantes",
    "nivel_cartao",
    "nivel_conta",
    "cancelamento_maq",
    "elegivel_c6",
    "safra_boleto",
    "idade_safra_boleto",
    "safra_maquina",
    "idade_safra_maquina",
    "metrica_ativacao",
    "metrica_progresso",
    "metrica_urgencia",
    "metrica_financeiro",
    "metrica_intencao",
    "score_perfil",
]


def normalize_column_name(name: str) -> str:
    normalized = unicodedata.normalize("NFKD", str(name)).encode("ascii", "ignore").decode("ascii")
    normalized = normalized.lower()
    normalized = normalized.replace("%", " pct ").replace("/", " ")
    normalized = re.sub(r"[^a-z0-9]+", "_", normalized)
    normalized = re.sub(r"_+", "_", normalized).strip("_")
    if normalized and normalized[0].isdigit():
        normalized = f"col_{normalized}"
    return normalized
